namespace Mathil

open System

module Colours =

    /// Represents a colour as RGB values.
    type Colour =
        {
            Red : byte;
            Green : byte;
            Blue : byte
        }

        /// Create colour from RGB values.
        static member fromRGB (r : byte, g : byte, b : byte) : Colour =
            { Red = r; Green = g; Blue = b }

        /// Create colour from #RRGGBB hex format.
        static member fromHex (hexCode : string) : Colour =
            let hexToDec (hex : string) =
                Convert.ToByte(Convert.ToInt32(hex, 16))

            let r = hexCode.[1..2]
            let g = hexCode.[3..4]
            let b = hexCode.[5..6]
        
            {
                Red = hexToDec r
                Green = hexToDec g
                Blue = hexToDec b
            }


    /// Linearly interpolates the red, green and blue values of the colour separately.
    let lerpColours (colour1 : Colour) (colour2 : Colour) (parameter : float) : Colour =

        let lerpBytes (startPoint : byte, endPoint : byte) : (float -> byte) =
            (fun t -> byte ((1.0 - t) * float startPoint + t * float endPoint))

        {
            Red = lerpBytes (colour1.Red, colour2.Red) parameter
            Green = lerpBytes (colour1.Green, colour1.Green) parameter
            Blue = lerpBytes (colour1.Blue, colour2.Blue) parameter
        }

    /// Mixes two colours together (not very successfully - it is recommended that colour mixing is done manually).
    let mixColours (colour1 : Colour) (colour2 : Colour) : Colour =
    
        let pigmentMix (pigment1 : byte) (pigment2 : byte) : byte =
            let part1 = float ((pown (255 - int pigment1) 2 + pown (255 - int pigment2) 2) / 2)
            byte (Math.Sqrt(part1))

        {
            Red = pigmentMix colour1.Red colour1.Red
            Green = pigmentMix colour1.Green colour1.Green
            Blue = pigmentMix colour1.Blue colour1.Blue
        }


    /// Consists of all colours in the CSS standard.
    type CSSColour =
        static member airForceBlueRaf = { Red = 93uy; Green = 138uy; Blue = 168uy } 
        static member airForceBlueUsaf = { Red = 0uy; Green = 48uy; Blue = 143uy } 
        static member airSuperiorityBlue = { Red = 114uy; Green = 160uy; Blue = 193uy } 
        static member alabamaCrimson = { Red = 163uy; Green = 38uy; Blue = 56uy } 
        static member aliceBlue = { Red = 240uy; Green = 248uy; Blue = 255uy } 
        static member alizarinCrimson = { Red = 227uy; Green = 38uy; Blue = 54uy } 
        static member alloyOrange = { Red = 196uy; Green = 98uy; Blue = 16uy } 
        static member almond = { Red = 239uy; Green = 222uy; Blue = 205uy } 
        static member amaranth = { Red = 229uy; Green = 43uy; Blue = 80uy } 
        static member amber = { Red = 255uy; Green = 191uy; Blue = 0uy } 
        static member amberSaeEce = { Red = 255uy; Green = 126uy; Blue = 0uy } 
        static member americanRose = { Red = 255uy; Green = 3uy; Blue = 62uy } 
        static member amethyst = { Red = 153uy; Green = 102uy; Blue = 204uy } 
        static member androidGreen = { Red = 164uy; Green = 198uy; Blue = 57uy } 
        static member antiFlashWhite = { Red = 242uy; Green = 243uy; Blue = 244uy } 
        static member antiqueBrass = { Red = 205uy; Green = 149uy; Blue = 117uy } 
        static member antiqueFuchsia = { Red = 145uy; Green = 92uy; Blue = 131uy } 
        static member antiqueRuby = { Red = 132uy; Green = 27uy; Blue = 45uy } 
        static member antiqueWhite = { Red = 250uy; Green = 235uy; Blue = 215uy } 
        static member aoEnglish = { Red = 0uy; Green = 128uy; Blue = 0uy } 
        static member appleGreen = { Red = 141uy; Green = 182uy; Blue = 0uy } 
        static member apricot = { Red = 251uy; Green = 206uy; Blue = 177uy } 
        static member aqua = { Red = 0uy; Green = 255uy; Blue = 255uy } 
        static member aquamarine = { Red = 127uy; Green = 255uy; Blue = 212uy } 
        static member armyGreen = { Red = 75uy; Green = 83uy; Blue = 32uy } 
        static member arsenic = { Red = 59uy; Green = 68uy; Blue = 75uy } 
        static member arylideYellow = { Red = 233uy; Green = 214uy; Blue = 107uy } 
        static member ashGrey = { Red = 178uy; Green = 190uy; Blue = 181uy } 
        static member asparagus = { Red = 135uy; Green = 169uy; Blue = 107uy } 
        static member atomicTangerine = { Red = 255uy; Green = 153uy; Blue = 102uy } 
        static member auburn = { Red = 165uy; Green = 42uy; Blue = 42uy } 
        static member aureolin = { Red = 253uy; Green = 238uy; Blue = 0uy } 
        static member aurometalsaurus = { Red = 110uy; Green = 127uy; Blue = 128uy } 
        static member avocado = { Red = 86uy; Green = 130uy; Blue = 3uy } 
        static member azure = { Red = 0uy; Green = 127uy; Blue = 255uy } 
        static member azureMistWeb = { Red = 240uy; Green = 255uy; Blue = 255uy } 
        static member babyBlue = { Red = 137uy; Green = 207uy; Blue = 240uy } 
        static member babyBlueEyes = { Red = 161uy; Green = 202uy; Blue = 241uy } 
        static member babyPink = { Red = 244uy; Green = 194uy; Blue = 194uy } 
        static member ballBlue = { Red = 33uy; Green = 171uy; Blue = 205uy } 
        static member bananaMania = { Red = 250uy; Green = 231uy; Blue = 181uy } 
        static member bananaYellow = { Red = 255uy; Green = 225uy; Blue = 53uy } 
        static member barnRed = { Red = 124uy; Green = 10uy; Blue = 2uy } 
        static member battleshipGrey = { Red = 132uy; Green = 132uy; Blue = 130uy } 
        static member bazaar = { Red = 152uy; Green = 119uy; Blue = 123uy } 
        static member beauBlue = { Red = 188uy; Green = 212uy; Blue = 230uy } 
        static member beaver = { Red = 159uy; Green = 129uy; Blue = 112uy } 
        static member beige = { Red = 245uy; Green = 245uy; Blue = 220uy } 
        static member bigDipORuby = { Red = 156uy; Green = 37uy; Blue = 66uy } 
        static member bisque = { Red = 255uy; Green = 228uy; Blue = 196uy } 
        static member bistre = { Red = 61uy; Green = 43uy; Blue = 31uy } 
        static member bittersweet = { Red = 254uy; Green = 111uy; Blue = 94uy } 
        static member bittersweetShimmer = { Red = 191uy; Green = 79uy; Blue = 81uy } 
        static member black = { Red = 0uy; Green = 0uy; Blue = 0uy } 
        static member blackBean = { Red = 61uy; Green = 12uy; Blue = 2uy } 
        static member blackLeatherJacket = { Red = 37uy; Green = 53uy; Blue = 41uy } 
        static member blackOlive = { Red = 59uy; Green = 60uy; Blue = 54uy } 
        static member blanchedAlmond = { Red = 255uy; Green = 235uy; Blue = 205uy } 
        static member blastOffBronze = { Red = 165uy; Green = 113uy; Blue = 100uy } 
        static member bleuDeFrance = { Red = 49uy; Green = 140uy; Blue = 231uy } 
        static member blizzardBlue = { Red = 172uy; Green = 229uy; Blue = 238uy } 
        static member blond = { Red = 250uy; Green = 240uy; Blue = 190uy } 
        static member blue = { Red = 0uy; Green = 0uy; Blue = 255uy } 
        static member blueBell = { Red = 162uy; Green = 162uy; Blue = 208uy } 
        static member blueCrayola = { Red = 31uy; Green = 117uy; Blue = 254uy } 
        static member blueGray = { Red = 102uy; Green = 153uy; Blue = 204uy } 
        static member blueGreen = { Red = 13uy; Green = 152uy; Blue = 186uy } 
        static member blueMunsell = { Red = 0uy; Green = 147uy; Blue = 175uy } 
        static member blueNcs = { Red = 0uy; Green = 135uy; Blue = 189uy } 
        static member bluePigment = { Red = 51uy; Green = 51uy; Blue = 153uy } 
        static member blueRyb = { Red = 2uy; Green = 71uy; Blue = 254uy } 
        static member blueSapphire = { Red = 18uy; Green = 97uy; Blue = 128uy } 
        static member blueViolet = { Red = 138uy; Green = 43uy; Blue = 226uy } 
        static member blush = { Red = 222uy; Green = 93uy; Blue = 131uy } 
        static member bole = { Red = 121uy; Green = 68uy; Blue = 59uy } 
        static member bondiBlue = { Red = 0uy; Green = 149uy; Blue = 182uy } 
        static member bone = { Red = 227uy; Green = 218uy; Blue = 201uy } 
        static member bostonUniversityRed = { Red = 204uy; Green = 0uy; Blue = 0uy } 
        static member bottleGreen = { Red = 0uy; Green = 106uy; Blue = 78uy } 
        static member boysenberry = { Red = 135uy; Green = 50uy; Blue = 96uy } 
        static member brandeisBlue = { Red = 0uy; Green = 112uy; Blue = 255uy } 
        static member brass = { Red = 181uy; Green = 166uy; Blue = 66uy } 
        static member brickRed = { Red = 203uy; Green = 65uy; Blue = 84uy } 
        static member brightCerulean = { Red = 29uy; Green = 172uy; Blue = 214uy } 
        static member brightGreen = { Red = 102uy; Green = 255uy; Blue = 0uy } 
        static member brightLavender = { Red = 191uy; Green = 148uy; Blue = 228uy } 
        static member brightMaroon = { Red = 195uy; Green = 33uy; Blue = 72uy } 
        static member brightPink = { Red = 255uy; Green = 0uy; Blue = 127uy } 
        static member brightTurquoise = { Red = 8uy; Green = 232uy; Blue = 222uy } 
        static member brightUbe = { Red = 209uy; Green = 159uy; Blue = 232uy } 
        static member brilliantLavender = { Red = 244uy; Green = 187uy; Blue = 255uy } 
        static member brilliantRose = { Red = 255uy; Green = 85uy; Blue = 163uy } 
        static member brinkPink = { Red = 251uy; Green = 96uy; Blue = 127uy } 
        static member britishRacingGreen = { Red = 0uy; Green = 66uy; Blue = 37uy } 
        static member bronze = { Red = 205uy; Green = 127uy; Blue = 50uy } 
        static member brownTraditional = { Red = 150uy; Green = 75uy; Blue = 0uy } 
        static member brownWeb = { Red = 165uy; Green = 42uy; Blue = 42uy } 
        static member bubbleGum = { Red = 255uy; Green = 193uy; Blue = 204uy } 
        static member bubbles = { Red = 231uy; Green = 254uy; Blue = 255uy } 
        static member buff = { Red = 240uy; Green = 220uy; Blue = 130uy } 
        static member bulgarianRose = { Red = 72uy; Green = 6uy; Blue = 7uy } 
        static member burgundy = { Red = 128uy; Green = 0uy; Blue = 32uy } 
        static member burlywood = { Red = 222uy; Green = 184uy; Blue = 135uy } 
        static member burntOrange = { Red = 204uy; Green = 85uy; Blue = 0uy } 
        static member burntSienna = { Red = 233uy; Green = 116uy; Blue = 81uy } 
        static member burntUmber = { Red = 138uy; Green = 51uy; Blue = 36uy } 
        static member byzantine = { Red = 189uy; Green = 51uy; Blue = 164uy } 
        static member byzantium = { Red = 112uy; Green = 41uy; Blue = 99uy } 
        static member cadet = { Red = 83uy; Green = 104uy; Blue = 114uy } 
        static member cadetBlue = { Red = 95uy; Green = 158uy; Blue = 160uy } 
        static member cadetGrey = { Red = 145uy; Green = 163uy; Blue = 176uy } 
        static member cadmiumGreen = { Red = 0uy; Green = 107uy; Blue = 60uy } 
        static member cadmiumOrange = { Red = 237uy; Green = 135uy; Blue = 45uy } 
        static member cadmiumRed = { Red = 227uy; Green = 0uy; Blue = 34uy } 
        static member cadmiumYellow = { Red = 255uy; Green = 246uy; Blue = 0uy } 
        static member cafAuLait = { Red = 166uy; Green = 123uy; Blue = 91uy } 
        static member cafNoir = { Red = 75uy; Green = 54uy; Blue = 33uy } 
        static member calPolyGreen = { Red = 30uy; Green = 77uy; Blue = 43uy } 
        static member cambridgeBlue = { Red = 163uy; Green = 193uy; Blue = 173uy } 
        static member camel = { Red = 193uy; Green = 154uy; Blue = 107uy } 
        static member cameoPink = { Red = 239uy; Green = 187uy; Blue = 204uy } 
        static member camouflageGreen = { Red = 120uy; Green = 134uy; Blue = 107uy } 
        static member canaryYellow = { Red = 255uy; Green = 239uy; Blue = 0uy } 
        static member candyAppleRed = { Red = 255uy; Green = 8uy; Blue = 0uy } 
        static member candyPink = { Red = 228uy; Green = 113uy; Blue = 122uy } 
        static member capri = { Red = 0uy; Green = 191uy; Blue = 255uy } 
        static member caputMortuum = { Red = 89uy; Green = 39uy; Blue = 32uy } 
        static member cardinal = { Red = 196uy; Green = 30uy; Blue = 58uy } 
        static member caribbeanGreen = { Red = 0uy; Green = 204uy; Blue = 153uy } 
        static member carmine = { Red = 150uy; Green = 0uy; Blue = 24uy } 
        static member carmineMP = { Red = 215uy; Green = 0uy; Blue = 64uy } 
        static member carminePink = { Red = 235uy; Green = 76uy; Blue = 66uy } 
        static member carmineRed = { Red = 255uy; Green = 0uy; Blue = 56uy } 
        static member carnationPink = { Red = 255uy; Green = 166uy; Blue = 201uy } 
        static member carnelian = { Red = 179uy; Green = 27uy; Blue = 27uy } 
        static member carolinaBlue = { Red = 153uy; Green = 186uy; Blue = 221uy } 
        static member carrotOrange = { Red = 237uy; Green = 145uy; Blue = 33uy } 
        static member catalinaBlue = { Red = 6uy; Green = 42uy; Blue = 120uy } 
        static member ceil = { Red = 146uy; Green = 161uy; Blue = 207uy } 
        static member celadon = { Red = 172uy; Green = 225uy; Blue = 175uy } 
        static member celadonBlue = { Red = 0uy; Green = 123uy; Blue = 167uy } 
        static member celadonGreen = { Red = 47uy; Green = 132uy; Blue = 124uy } 
        static member celesteColour = { Red = 178uy; Green = 255uy; Blue = 255uy } 
        static member celestialBlue = { Red = 73uy; Green = 151uy; Blue = 208uy } 
        static member cerise = { Red = 222uy; Green = 49uy; Blue = 99uy } 
        static member cerisePink = { Red = 236uy; Green = 59uy; Blue = 131uy } 
        static member cerulean = { Red = 0uy; Green = 123uy; Blue = 167uy } 
        static member ceruleanBlue = { Red = 42uy; Green = 82uy; Blue = 190uy } 
        static member ceruleanFrost = { Red = 109uy; Green = 155uy; Blue = 195uy } 
        static member cgBlue = { Red = 0uy; Green = 122uy; Blue = 165uy } 
        static member cgRed = { Red = 224uy; Green = 60uy; Blue = 49uy } 
        static member chamoisee = { Red = 160uy; Green = 120uy; Blue = 90uy } 
        static member champagne = { Red = 250uy; Green = 214uy; Blue = 165uy } 
        static member charcoal = { Red = 54uy; Green = 69uy; Blue = 79uy } 
        static member charmPink = { Red = 230uy; Green = 143uy; Blue = 172uy } 
        static member chartreuseTraditional = { Red = 223uy; Green = 255uy; Blue = 0uy } 
        static member chartreuseWeb = { Red = 127uy; Green = 255uy; Blue = 0uy } 
        static member cherry = { Red = 222uy; Green = 49uy; Blue = 99uy } 
        static member cherryBlossomPink = { Red = 255uy; Green = 183uy; Blue = 197uy } 
        static member chestnut = { Red = 205uy; Green = 92uy; Blue = 92uy } 
        static member chinaPink = { Red = 222uy; Green = 111uy; Blue = 161uy } 
        static member chinaRose = { Red = 168uy; Green = 81uy; Blue = 110uy } 
        static member chineseRed = { Red = 170uy; Green = 56uy; Blue = 30uy } 
        static member chocolateTraditional = { Red = 123uy; Green = 63uy; Blue = 0uy } 
        static member chocolateWeb = { Red = 210uy; Green = 105uy; Blue = 30uy } 
        static member chromeYellow = { Red = 255uy; Green = 167uy; Blue = 0uy } 
        static member cinereous = { Red = 152uy; Green = 129uy; Blue = 123uy } 
        static member cinnabar = { Red = 227uy; Green = 66uy; Blue = 52uy } 
        static member cinnamon = { Red = 210uy; Green = 105uy; Blue = 30uy } 
        static member citrine = { Red = 228uy; Green = 208uy; Blue = 10uy } 
        static member classicRose = { Red = 251uy; Green = 204uy; Blue = 231uy } 
        static member cobalt = { Red = 0uy; Green = 71uy; Blue = 171uy } 
        static member cocoaBrown = { Red = 210uy; Green = 105uy; Blue = 30uy } 
        static member coffee = { Red = 111uy; Green = 78uy; Blue = 55uy } 
        static member columbiaBlue = { Red = 155uy; Green = 221uy; Blue = 255uy } 
        static member congoPink = { Red = 248uy; Green = 131uy; Blue = 121uy } 
        static member coolBlack = { Red = 0uy; Green = 46uy; Blue = 99uy } 
        static member coolGrey = { Red = 140uy; Green = 146uy; Blue = 172uy } 
        static member copper = { Red = 184uy; Green = 115uy; Blue = 51uy } 
        static member copperCrayola = { Red = 218uy; Green = 138uy; Blue = 103uy } 
        static member copperPenny = { Red = 173uy; Green = 111uy; Blue = 105uy } 
        static member copperRed = { Red = 203uy; Green = 109uy; Blue = 81uy } 
        static member copperRose = { Red = 153uy; Green = 102uy; Blue = 102uy } 
        static member coquelicot = { Red = 255uy; Green = 56uy; Blue = 0uy } 
        static member coral = { Red = 255uy; Green = 127uy; Blue = 80uy } 
        static member coralPink = { Red = 248uy; Green = 131uy; Blue = 121uy } 
        static member coralRed = { Red = 255uy; Green = 64uy; Blue = 64uy } 
        static member cordovan = { Red = 137uy; Green = 63uy; Blue = 69uy } 
        static member corn = { Red = 251uy; Green = 236uy; Blue = 93uy } 
        static member cornellRed = { Red = 179uy; Green = 27uy; Blue = 27uy } 
        static member cornflowerBlue = { Red = 100uy; Green = 149uy; Blue = 237uy } 
        static member cornsilk = { Red = 255uy; Green = 248uy; Blue = 220uy } 
        static member cosmicLatte = { Red = 255uy; Green = 248uy; Blue = 231uy } 
        static member cottonCandy = { Red = 255uy; Green = 188uy; Blue = 217uy } 
        static member cream = { Red = 255uy; Green = 253uy; Blue = 208uy } 
        static member crimson = { Red = 220uy; Green = 20uy; Blue = 60uy } 
        static member crimsonGlory = { Red = 190uy; Green = 0uy; Blue = 50uy } 
        static member cyan = { Red = 0uy; Green = 255uy; Blue = 255uy } 
        static member cyanProcess = { Red = 0uy; Green = 183uy; Blue = 235uy } 
        static member daffodil = { Red = 255uy; Green = 255uy; Blue = 49uy } 
        static member dandelion = { Red = 240uy; Green = 225uy; Blue = 48uy } 
        static member darkBlue = { Red = 0uy; Green = 0uy; Blue = 139uy } 
        static member darkBrown = { Red = 101uy; Green = 67uy; Blue = 33uy } 
        static member darkByzantium = { Red = 93uy; Green = 57uy; Blue = 84uy } 
        static member darkCandyAppleRed = { Red = 164uy; Green = 0uy; Blue = 0uy } 
        static member darkCerulean = { Red = 8uy; Green = 69uy; Blue = 126uy } 
        static member darkChestnut = { Red = 152uy; Green = 105uy; Blue = 96uy } 
        static member darkCoral = { Red = 205uy; Green = 91uy; Blue = 69uy } 
        static member darkCyan = { Red = 0uy; Green = 139uy; Blue = 139uy } 
        static member darkElectricBlue = { Red = 83uy; Green = 104uy; Blue = 120uy } 
        static member darkGoldenrod = { Red = 184uy; Green = 134uy; Blue = 11uy } 
        static member darkGray = { Red = 169uy; Green = 169uy; Blue = 169uy } 
        static member darkGreen = { Red = 1uy; Green = 50uy; Blue = 32uy } 
        static member darkImperialBlue = { Red = 0uy; Green = 65uy; Blue = 106uy } 
        static member darkJungleGreen = { Red = 26uy; Green = 36uy; Blue = 33uy } 
        static member darkKhaki = { Red = 189uy; Green = 183uy; Blue = 107uy } 
        static member darkLava = { Red = 72uy; Green = 60uy; Blue = 50uy } 
        static member darkLavender = { Red = 115uy; Green = 79uy; Blue = 150uy } 
        static member darkMagenta = { Red = 139uy; Green = 0uy; Blue = 139uy } 
        static member darkMidnightBlue = { Red = 0uy; Green = 51uy; Blue = 102uy } 
        static member darkOliveGreen = { Red = 85uy; Green = 107uy; Blue = 47uy } 
        static member darkOrange = { Red = 255uy; Green = 140uy; Blue = 0uy } 
        static member darkOrchid = { Red = 153uy; Green = 50uy; Blue = 204uy } 
        static member darkPastelBlue = { Red = 119uy; Green = 158uy; Blue = 203uy } 
        static member darkPastelGreen = { Red = 3uy; Green = 192uy; Blue = 60uy } 
        static member darkPastelPurple = { Red = 150uy; Green = 111uy; Blue = 214uy } 
        static member darkPastelRed = { Red = 194uy; Green = 59uy; Blue = 34uy } 
        static member darkPink = { Red = 231uy; Green = 84uy; Blue = 128uy } 
        static member darkPowderBlue = { Red = 0uy; Green = 51uy; Blue = 153uy } 
        static member darkRaspberry = { Red = 135uy; Green = 38uy; Blue = 87uy } 
        static member darkRed = { Red = 139uy; Green = 0uy; Blue = 0uy } 
        static member darkSalmon = { Red = 233uy; Green = 150uy; Blue = 122uy } 
        static member darkScarlet = { Red = 86uy; Green = 3uy; Blue = 25uy } 
        static member darkSeaGreen = { Red = 143uy; Green = 188uy; Blue = 143uy } 
        static member darkSienna = { Red = 60uy; Green = 20uy; Blue = 20uy } 
        static member darkSlateBlue = { Red = 72uy; Green = 61uy; Blue = 139uy } 
        static member darkSlateGray = { Red = 47uy; Green = 79uy; Blue = 79uy } 
        static member darkSpringGreen = { Red = 23uy; Green = 114uy; Blue = 69uy } 
        static member darkTan = { Red = 145uy; Green = 129uy; Blue = 81uy } 
        static member darkTangerine = { Red = 255uy; Green = 168uy; Blue = 18uy } 
        static member darkTaupe = { Red = 72uy; Green = 60uy; Blue = 50uy } 
        static member darkTerraCotta = { Red = 204uy; Green = 78uy; Blue = 92uy } 
        static member darkTurquoise = { Red = 0uy; Green = 206uy; Blue = 209uy } 
        static member darkViolet = { Red = 148uy; Green = 0uy; Blue = 211uy } 
        static member darkYellow = { Red = 155uy; Green = 135uy; Blue = 12uy } 
        static member dartmouthGreen = { Red = 0uy; Green = 112uy; Blue = 60uy } 
        static member davySGrey = { Red = 85uy; Green = 85uy; Blue = 85uy } 
        static member debianRed = { Red = 215uy; Green = 10uy; Blue = 83uy } 
        static member deepCarmine = { Red = 169uy; Green = 32uy; Blue = 62uy } 
        static member deepCarminePink = { Red = 239uy; Green = 48uy; Blue = 56uy } 
        static member deepCarrotOrange = { Red = 233uy; Green = 105uy; Blue = 44uy } 
        static member deepCerise = { Red = 218uy; Green = 50uy; Blue = 135uy } 
        static member deepChampagne = { Red = 250uy; Green = 214uy; Blue = 165uy } 
        static member deepChestnut = { Red = 185uy; Green = 78uy; Blue = 72uy } 
        static member deepCoffee = { Red = 112uy; Green = 66uy; Blue = 65uy } 
        static member deepFuchsia = { Red = 193uy; Green = 84uy; Blue = 193uy } 
        static member deepJungleGreen = { Red = 0uy; Green = 75uy; Blue = 73uy } 
        static member deepLilac = { Red = 153uy; Green = 85uy; Blue = 187uy } 
        static member deepMagenta = { Red = 204uy; Green = 0uy; Blue = 204uy } 
        static member deepPeach = { Red = 255uy; Green = 203uy; Blue = 164uy } 
        static member deepPink = { Red = 255uy; Green = 20uy; Blue = 147uy } 
        static member deepRuby = { Red = 132uy; Green = 63uy; Blue = 91uy } 
        static member deepSaffron = { Red = 255uy; Green = 153uy; Blue = 51uy } 
        static member deepSkyBlue = { Red = 0uy; Green = 191uy; Blue = 255uy } 
        static member deepTuscanRed = { Red = 102uy; Green = 66uy; Blue = 77uy } 
        static member denim = { Red = 21uy; Green = 96uy; Blue = 189uy } 
        static member desert = { Red = 193uy; Green = 154uy; Blue = 107uy } 
        static member desertSand = { Red = 237uy; Green = 201uy; Blue = 175uy } 
        static member dimGray = { Red = 105uy; Green = 105uy; Blue = 105uy } 
        static member dodgerBlue = { Red = 30uy; Green = 144uy; Blue = 255uy } 
        static member dogwoodRose = { Red = 215uy; Green = 24uy; Blue = 104uy } 
        static member dollarBill = { Red = 133uy; Green = 187uy; Blue = 101uy } 
        static member drab = { Red = 150uy; Green = 113uy; Blue = 23uy } 
        static member dukeBlue = { Red = 0uy; Green = 0uy; Blue = 156uy } 
        static member earthYellow = { Red = 225uy; Green = 169uy; Blue = 95uy } 
        static member ebony = { Red = 85uy; Green = 93uy; Blue = 80uy } 
        static member ecru = { Red = 194uy; Green = 178uy; Blue = 128uy } 
        static member eggplant = { Red = 97uy; Green = 64uy; Blue = 81uy } 
        static member eggshell = { Red = 240uy; Green = 234uy; Blue = 214uy } 
        static member egyptianBlue = { Red = 16uy; Green = 52uy; Blue = 166uy } 
        static member electricBlue = { Red = 125uy; Green = 249uy; Blue = 255uy } 
        static member electricCrimson = { Red = 255uy; Green = 0uy; Blue = 63uy } 
        static member electricCyan = { Red = 0uy; Green = 255uy; Blue = 255uy } 
        static member electricGreen = { Red = 0uy; Green = 255uy; Blue = 0uy } 
        static member electricIndigo = { Red = 111uy; Green = 0uy; Blue = 255uy } 
        static member electricLavender = { Red = 244uy; Green = 187uy; Blue = 255uy } 
        static member electricLime = { Red = 204uy; Green = 255uy; Blue = 0uy } 
        static member electricPurple = { Red = 191uy; Green = 0uy; Blue = 255uy } 
        static member electricUltramarine = { Red = 63uy; Green = 0uy; Blue = 255uy } 
        static member electricViolet = { Red = 143uy; Green = 0uy; Blue = 255uy } 
        static member electricYellow = { Red = 255uy; Green = 255uy; Blue = 0uy } 
        static member emerald = { Red = 80uy; Green = 200uy; Blue = 120uy } 
        static member englishLavender = { Red = 180uy; Green = 131uy; Blue = 149uy } 
        static member etonBlue = { Red = 150uy; Green = 200uy; Blue = 162uy } 
        static member fallow = { Red = 193uy; Green = 154uy; Blue = 107uy } 
        static member faluRed = { Red = 128uy; Green = 24uy; Blue = 24uy } 
        static member fandango = { Red = 181uy; Green = 51uy; Blue = 137uy } 
        static member fashionFuchsia = { Red = 244uy; Green = 0uy; Blue = 161uy } 
        static member fawn = { Red = 229uy; Green = 170uy; Blue = 112uy } 
        static member feldgrau = { Red = 77uy; Green = 93uy; Blue = 83uy } 
        static member fernGreen = { Red = 79uy; Green = 121uy; Blue = 66uy } 
        static member ferrariRed = { Red = 255uy; Green = 40uy; Blue = 0uy } 
        static member fieldDrab = { Red = 108uy; Green = 84uy; Blue = 30uy } 
        static member fireEngineRed = { Red = 206uy; Green = 32uy; Blue = 41uy } 
        static member firebrick = { Red = 178uy; Green = 34uy; Blue = 34uy } 
        static member flame = { Red = 226uy; Green = 88uy; Blue = 34uy } 
        static member flamingoPink = { Red = 252uy; Green = 142uy; Blue = 172uy } 
        static member flavescent = { Red = 247uy; Green = 233uy; Blue = 142uy } 
        static member flax = { Red = 238uy; Green = 220uy; Blue = 130uy } 
        static member floralWhite = { Red = 255uy; Green = 250uy; Blue = 240uy } 
        static member fluorescentOrange = { Red = 255uy; Green = 191uy; Blue = 0uy } 
        static member fluorescentPink = { Red = 255uy; Green = 20uy; Blue = 147uy } 
        static member fluorescentYellow = { Red = 204uy; Green = 255uy; Blue = 0uy } 
        static member folly = { Red = 255uy; Green = 0uy; Blue = 79uy } 
        static member forestGreenTraditional = { Red = 1uy; Green = 68uy; Blue = 33uy } 
        static member forestGreenWeb = { Red = 34uy; Green = 139uy; Blue = 34uy } 
        static member frenchBeige = { Red = 166uy; Green = 123uy; Blue = 91uy } 
        static member frenchBlue = { Red = 0uy; Green = 114uy; Blue = 187uy } 
        static member frenchLilac = { Red = 134uy; Green = 96uy; Blue = 142uy } 
        static member frenchLime = { Red = 204uy; Green = 255uy; Blue = 0uy } 
        static member frenchRaspberry = { Red = 199uy; Green = 44uy; Blue = 72uy } 
        static member frenchRose = { Red = 246uy; Green = 74uy; Blue = 138uy } 
        static member fuchsia = { Red = 255uy; Green = 0uy; Blue = 255uy } 
        static member fuchsiaCrayola = { Red = 193uy; Green = 84uy; Blue = 193uy } 
        static member fuchsiaPink = { Red = 255uy; Green = 119uy; Blue = 255uy } 
        static member fuchsiaRose = { Red = 199uy; Green = 67uy; Blue = 117uy } 
        static member fulvous = { Red = 228uy; Green = 132uy; Blue = 0uy } 
        static member fuzzyWuzzy = { Red = 204uy; Green = 102uy; Blue = 102uy } 
        static member gainsboro = { Red = 220uy; Green = 220uy; Blue = 220uy } 
        static member gamboge = { Red = 228uy; Green = 155uy; Blue = 15uy } 
        static member ghostWhite = { Red = 248uy; Green = 248uy; Blue = 255uy } 
        static member ginger = { Red = 176uy; Green = 101uy; Blue = 0uy } 
        static member glaucous = { Red = 96uy; Green = 130uy; Blue = 182uy } 
        static member glitter = { Red = 230uy; Green = 232uy; Blue = 250uy } 
        static member goldMetallic = { Red = 212uy; Green = 175uy; Blue = 55uy } 
        static member goldWebGolden = { Red = 255uy; Green = 215uy; Blue = 0uy } 
        static member goldenBrown = { Red = 153uy; Green = 101uy; Blue = 21uy } 
        static member goldenPoppy = { Red = 252uy; Green = 194uy; Blue = 0uy } 
        static member goldenYellow = { Red = 255uy; Green = 223uy; Blue = 0uy } 
        static member goldenrod = { Red = 218uy; Green = 165uy; Blue = 32uy } 
        static member grannySmithApple = { Red = 168uy; Green = 228uy; Blue = 160uy } 
        static member gray = { Red = 128uy; Green = 128uy; Blue = 128uy } 
        static member grayAsparagus = { Red = 70uy; Green = 89uy; Blue = 69uy } 
        static member grayHtmlCssGray = { Red = 128uy; Green = 128uy; Blue = 128uy } 
        static member grayX11Gray = { Red = 190uy; Green = 190uy; Blue = 190uy } 
        static member greenColorWheelX11Green = { Red = 0uy; Green = 255uy; Blue = 0uy } 
        static member greenCrayola = { Red = 28uy; Green = 172uy; Blue = 120uy } 
        static member greenHtmlCssGreen = { Red = 0uy; Green = 128uy; Blue = 0uy } 
        static member greenMunsell = { Red = 0uy; Green = 168uy; Blue = 119uy } 
        static member greenNcs = { Red = 0uy; Green = 159uy; Blue = 107uy } 
        static member greenPigment = { Red = 0uy; Green = 165uy; Blue = 80uy } 
        static member greenRyb = { Red = 102uy; Green = 176uy; Blue = 50uy } 
        static member greenYellow = { Red = 173uy; Green = 255uy; Blue = 47uy } 
        static member grullo = { Red = 169uy; Green = 154uy; Blue = 134uy } 
        static member guppieGreen = { Red = 0uy; Green = 255uy; Blue = 127uy } 
        static member halayBe = { Red = 102uy; Green = 56uy; Blue = 84uy } 
        static member hanBlue = { Red = 68uy; Green = 108uy; Blue = 207uy } 
        static member hanPurple = { Red = 82uy; Green = 24uy; Blue = 250uy } 
        static member hansaYellow = { Red = 233uy; Green = 214uy; Blue = 107uy } 
        static member harlequin = { Red = 63uy; Green = 255uy; Blue = 0uy } 
        static member harvardCrimson = { Red = 201uy; Green = 0uy; Blue = 22uy } 
        static member harvestGold = { Red = 218uy; Green = 145uy; Blue = 0uy } 
        static member heartGold = { Red = 128uy; Green = 128uy; Blue = 0uy } 
        static member heliotrope = { Red = 223uy; Green = 115uy; Blue = 255uy } 
        static member hollywoodCerise = { Red = 244uy; Green = 0uy; Blue = 161uy } 
        static member honeydew = { Red = 240uy; Green = 255uy; Blue = 240uy } 
        static member honoluluBlue = { Red = 0uy; Green = 127uy; Blue = 191uy } 
        static member hookerSGreen = { Red = 73uy; Green = 121uy; Blue = 107uy } 
        static member hotMagenta = { Red = 255uy; Green = 29uy; Blue = 206uy } 
        static member hotPink = { Red = 255uy; Green = 105uy; Blue = 180uy } 
        static member hunterGreen = { Red = 53uy; Green = 94uy; Blue = 59uy } 
        static member iceberg = { Red = 113uy; Green = 166uy; Blue = 210uy } 
        static member icterine = { Red = 252uy; Green = 247uy; Blue = 94uy } 
        static member imperialBlue = { Red = 0uy; Green = 35uy; Blue = 149uy } 
        static member inchworm = { Red = 178uy; Green = 236uy; Blue = 93uy } 
        static member indiaGreen = { Red = 19uy; Green = 136uy; Blue = 8uy } 
        static member indianRed = { Red = 205uy; Green = 92uy; Blue = 92uy } 
        static member indianYellow = { Red = 227uy; Green = 168uy; Blue = 87uy } 
        static member indigo = { Red = 111uy; Green = 0uy; Blue = 255uy } 
        static member indigoDye = { Red = 0uy; Green = 65uy; Blue = 106uy } 
        static member indigoWeb = { Red = 75uy; Green = 0uy; Blue = 130uy } 
        static member internationalKleinBlue = { Red = 0uy; Green = 47uy; Blue = 167uy } 
        static member internationalOrangeAerospace = { Red = 255uy; Green = 79uy; Blue = 0uy } 
        static member internationalOrangeEngineering = { Red = 186uy; Green = 22uy; Blue = 12uy } 
        static member internationalOrangeGoldenGateBridge = { Red = 192uy; Green = 54uy; Blue = 44uy }
        static member iris = { Red = 90uy; Green = 79uy; Blue = 207uy } 
        static member isabelline = { Red = 244uy; Green = 240uy; Blue = 236uy } 
        static member islamicGreen = { Red = 0uy; Green = 144uy; Blue = 0uy } 
        static member ivory = { Red = 255uy; Green = 255uy; Blue = 240uy } 
        static member jade = { Red = 0uy; Green = 168uy; Blue = 107uy } 
        static member jasmine = { Red = 248uy; Green = 222uy; Blue = 126uy } 
        static member jasper = { Red = 215uy; Green = 59uy; Blue = 62uy } 
        static member jazzberryJam = { Red = 165uy; Green = 11uy; Blue = 94uy } 
        static member jet = { Red = 52uy; Green = 52uy; Blue = 52uy } 
        static member jonquil = { Red = 250uy; Green = 218uy; Blue = 94uy } 
        static member juneBud = { Red = 189uy; Green = 218uy; Blue = 87uy } 
        static member jungleGreen = { Red = 41uy; Green = 171uy; Blue = 135uy } 
        static member kellyGreen = { Red = 76uy; Green = 187uy; Blue = 23uy } 
        static member kenyanCopper = { Red = 124uy; Green = 28uy; Blue = 5uy } 
        static member khakiHtmlCssKhaki = { Red = 195uy; Green = 176uy; Blue = 145uy } 
        static member khakiX11LightKhaki = { Red = 240uy; Green = 230uy; Blue = 140uy } 
        static member kuCrimson = { Red = 232uy; Green = 0uy; Blue = 13uy } 
        static member laSalleGreen = { Red = 8uy; Green = 120uy; Blue = 48uy } 
        static member languidLavender = { Red = 214uy; Green = 202uy; Blue = 221uy } 
        static member lapisLazuli = { Red = 38uy; Green = 97uy; Blue = 156uy } 
        static member laserLemon = { Red = 254uy; Green = 254uy; Blue = 34uy } 
        static member laurelGreen = { Red = 169uy; Green = 186uy; Blue = 157uy } 
        static member lava = { Red = 207uy; Green = 16uy; Blue = 32uy } 
        static member lavenderBlue = { Red = 204uy; Green = 204uy; Blue = 255uy } 
        static member lavenderBlush = { Red = 255uy; Green = 240uy; Blue = 245uy } 
        static member lavenderFloral = { Red = 181uy; Green = 126uy; Blue = 220uy } 
        static member lavenderGray = { Red = 196uy; Green = 195uy; Blue = 208uy } 
        static member lavenderIndigo = { Red = 148uy; Green = 87uy; Blue = 235uy } 
        static member lavenderMagenta = { Red = 238uy; Green = 130uy; Blue = 238uy } 
        static member lavenderMist = { Red = 230uy; Green = 230uy; Blue = 250uy } 
        static member lavenderPink = { Red = 251uy; Green = 174uy; Blue = 210uy } 
        static member lavenderPurple = { Red = 150uy; Green = 123uy; Blue = 182uy } 
        static member lavenderRose = { Red = 251uy; Green = 160uy; Blue = 227uy } 
        static member lavenderWeb = { Red = 230uy; Green = 230uy; Blue = 250uy } 
        static member lawnGreen = { Red = 124uy; Green = 252uy; Blue = 0uy } 
        static member lemon = { Red = 255uy; Green = 247uy; Blue = 0uy } 
        static member lemonChiffon = { Red = 255uy; Green = 250uy; Blue = 205uy } 
        static member lemonLime = { Red = 227uy; Green = 255uy; Blue = 0uy } 
        static member licorice = { Red = 26uy; Green = 17uy; Blue = 16uy } 
        static member lightApricot = { Red = 253uy; Green = 213uy; Blue = 177uy } 
        static member lightBlue = { Red = 173uy; Green = 216uy; Blue = 230uy } 
        static member lightBrown = { Red = 181uy; Green = 101uy; Blue = 29uy } 
        static member lightCarminePink = { Red = 230uy; Green = 103uy; Blue = 113uy } 
        static member lightCoral = { Red = 240uy; Green = 128uy; Blue = 128uy } 
        static member lightCornflowerBlue = { Red = 147uy; Green = 204uy; Blue = 234uy } 
        static member lightCrimson = { Red = 245uy; Green = 105uy; Blue = 145uy } 
        static member lightCyan = { Red = 224uy; Green = 255uy; Blue = 255uy } 
        static member lightFuchsiaPink = { Red = 249uy; Green = 132uy; Blue = 239uy } 
        static member lightGoldenrodYellow = { Red = 250uy; Green = 250uy; Blue = 210uy } 
        static member lightGray = { Red = 211uy; Green = 211uy; Blue = 211uy } 
        static member lightGreen = { Red = 144uy; Green = 238uy; Blue = 144uy } 
        static member lightKhaki = { Red = 240uy; Green = 230uy; Blue = 140uy } 
        static member lightPastelPurple = { Red = 177uy; Green = 156uy; Blue = 217uy } 
        static member lightPink = { Red = 255uy; Green = 182uy; Blue = 193uy } 
        static member lightRedOchre = { Red = 233uy; Green = 116uy; Blue = 81uy } 
        static member lightSalmon = { Red = 255uy; Green = 160uy; Blue = 122uy } 
        static member lightSalmonPink = { Red = 255uy; Green = 153uy; Blue = 153uy } 
        static member lightSeaGreen = { Red = 32uy; Green = 178uy; Blue = 170uy } 
        static member lightSkyBlue = { Red = 135uy; Green = 206uy; Blue = 250uy } 
        static member lightSlateGray = { Red = 119uy; Green = 136uy; Blue = 153uy } 
        static member lightTaupe = { Red = 179uy; Green = 139uy; Blue = 109uy } 
        static member lightThulianPink = { Red = 230uy; Green = 143uy; Blue = 172uy } 
        static member lightYellow = { Red = 255uy; Green = 255uy; Blue = 224uy } 
        static member lilac = { Red = 200uy; Green = 162uy; Blue = 200uy } 
        static member limeColorWheel = { Red = 191uy; Green = 255uy; Blue = 0uy } 
        static member limeGreen = { Red = 50uy; Green = 205uy; Blue = 50uy } 
        static member limeWebX11Green = { Red = 0uy; Green = 255uy; Blue = 0uy } 
        static member limerick = { Red = 157uy; Green = 194uy; Blue = 9uy } 
        static member lincolnGreen = { Red = 25uy; Green = 89uy; Blue = 5uy } 
        static member linen = { Red = 250uy; Green = 240uy; Blue = 230uy } 
        static member lion = { Red = 193uy; Green = 154uy; Blue = 107uy } 
        static member littleBoyBlue = { Red = 108uy; Green = 160uy; Blue = 220uy } 
        static member liver = { Red = 83uy; Green = 75uy; Blue = 79uy } 
        static member lust = { Red = 230uy; Green = 32uy; Blue = 32uy } 
        static member magenta = { Red = 255uy; Green = 0uy; Blue = 255uy } 
        static member magentaDye = { Red = 202uy; Green = 31uy; Blue = 123uy } 
        static member magentaProcess = { Red = 255uy; Green = 0uy; Blue = 144uy } 
        static member magicMint = { Red = 170uy; Green = 240uy; Blue = 209uy } 
        static member magnolia = { Red = 248uy; Green = 244uy; Blue = 255uy } 
        static member mahogany = { Red = 192uy; Green = 64uy; Blue = 0uy } 
        static member maize = { Red = 251uy; Green = 236uy; Blue = 93uy } 
        static member majorelleBlue = { Red = 96uy; Green = 80uy; Blue = 220uy } 
        static member malachite = { Red = 11uy; Green = 218uy; Blue = 81uy } 
        static member manatee = { Red = 151uy; Green = 154uy; Blue = 170uy } 
        static member mangoTango = { Red = 255uy; Green = 130uy; Blue = 67uy } 
        static member mantis = { Red = 116uy; Green = 195uy; Blue = 101uy } 
        static member mardiGras = { Red = 136uy; Green = 0uy; Blue = 133uy } 
        static member maroonCrayola = { Red = 195uy; Green = 33uy; Blue = 72uy } 
        static member maroonHtmlCss = { Red = 128uy; Green = 0uy; Blue = 0uy } 
        static member maroonX11 = { Red = 176uy; Green = 48uy; Blue = 96uy } 
        static member mauve = { Red = 224uy; Green = 176uy; Blue = 255uy } 
        static member mauveTaupe = { Red = 145uy; Green = 95uy; Blue = 109uy } 
        static member mauvelous = { Red = 239uy; Green = 152uy; Blue = 170uy } 
        static member mayaBlue = { Red = 115uy; Green = 194uy; Blue = 251uy } 
        static member meatBrown = { Red = 229uy; Green = 183uy; Blue = 59uy } 
        static member mediumAquamarine = { Red = 102uy; Green = 221uy; Blue = 170uy } 
        static member mediumBlue = { Red = 0uy; Green = 0uy; Blue = 205uy } 
        static member mediumCandyAppleRed = { Red = 226uy; Green = 6uy; Blue = 44uy } 
        static member mediumCarmine = { Red = 175uy; Green = 64uy; Blue = 53uy } 
        static member mediumChampagne = { Red = 243uy; Green = 229uy; Blue = 171uy } 
        static member mediumElectricBlue = { Red = 3uy; Green = 80uy; Blue = 150uy } 
        static member mediumJungleGreen = { Red = 28uy; Green = 53uy; Blue = 45uy } 
        static member mediumLavenderMagenta = { Red = 221uy; Green = 160uy; Blue = 221uy } 
        static member mediumOrchid = { Red = 186uy; Green = 85uy; Blue = 211uy } 
        static member mediumPersianBlue = { Red = 0uy; Green = 103uy; Blue = 165uy } 
        static member mediumPurple = { Red = 147uy; Green = 112uy; Blue = 219uy } 
        static member mediumRedViolet = { Red = 187uy; Green = 51uy; Blue = 133uy } 
        static member mediumRuby = { Red = 170uy; Green = 64uy; Blue = 105uy } 
        static member mediumSeaGreen = { Red = 60uy; Green = 179uy; Blue = 113uy } 
        static member mediumSlateBlue = { Red = 123uy; Green = 104uy; Blue = 238uy } 
        static member mediumSpringBud = { Red = 201uy; Green = 220uy; Blue = 135uy } 
        static member mediumSpringGreen = { Red = 0uy; Green = 250uy; Blue = 154uy } 
        static member mediumTaupe = { Red = 103uy; Green = 76uy; Blue = 71uy } 
        static member mediumTurquoise = { Red = 72uy; Green = 209uy; Blue = 204uy } 
        static member mediumTuscanRed = { Red = 121uy; Green = 68uy; Blue = 59uy } 
        static member mediumVermilion = { Red = 217uy; Green = 96uy; Blue = 59uy } 
        static member mediumVioletRed = { Red = 199uy; Green = 21uy; Blue = 133uy } 
        static member mellowApricot = { Red = 248uy; Green = 184uy; Blue = 120uy } 
        static member mellowYellow = { Red = 248uy; Green = 222uy; Blue = 126uy } 
        static member melon = { Red = 253uy; Green = 188uy; Blue = 180uy } 
        static member midnightBlue = { Red = 25uy; Green = 25uy; Blue = 112uy } 
        static member midnightGreenEagleGreen = { Red = 0uy; Green = 73uy; Blue = 83uy } 
        static member mikadoYellow = { Red = 255uy; Green = 196uy; Blue = 12uy } 
        static member mint = { Red = 62uy; Green = 180uy; Blue = 137uy } 
        static member mintCream = { Red = 245uy; Green = 255uy; Blue = 250uy } 
        static member mintGreen = { Red = 152uy; Green = 255uy; Blue = 152uy } 
        static member mistyRose = { Red = 255uy; Green = 228uy; Blue = 225uy } 
        static member moccasin = { Red = 250uy; Green = 235uy; Blue = 215uy } 
        static member modeBeige = { Red = 150uy; Green = 113uy; Blue = 23uy } 
        static member moonstoneBlue = { Red = 115uy; Green = 169uy; Blue = 194uy } 
        static member mordantRed19 = { Red = 174uy; Green = 12uy; Blue = 0uy } 
        static member mossGreen = { Red = 173uy; Green = 223uy; Blue = 173uy } 
        static member mountainMeadow = { Red = 48uy; Green = 186uy; Blue = 143uy } 
        static member mountbattenPink = { Red = 153uy; Green = 122uy; Blue = 141uy } 
        static member msuGreen = { Red = 24uy; Green = 69uy; Blue = 59uy } 
        static member mulberry = { Red = 197uy; Green = 75uy; Blue = 140uy } 
        static member mustard = { Red = 255uy; Green = 219uy; Blue = 88uy } 
        static member myrtle = { Red = 33uy; Green = 66uy; Blue = 30uy } 
        static member nadeshikoPink = { Red = 246uy; Green = 173uy; Blue = 198uy } 
        static member napierGreen = { Red = 42uy; Green = 128uy; Blue = 0uy } 
        static member naplesYellow = { Red = 250uy; Green = 218uy; Blue = 94uy } 
        static member navajoWhite = { Red = 255uy; Green = 222uy; Blue = 173uy } 
        static member navyBlue = { Red = 0uy; Green = 0uy; Blue = 128uy } 
        static member neonCarrot = { Red = 255uy; Green = 163uy; Blue = 67uy } 
        static member neonFuchsia = { Red = 254uy; Green = 65uy; Blue = 100uy } 
        static member neonGreen = { Red = 57uy; Green = 255uy; Blue = 20uy } 
        static member newYorkPink = { Red = 215uy; Green = 131uy; Blue = 127uy } 
        static member nonPhotoBlue = { Red = 164uy; Green = 221uy; Blue = 237uy } 
        static member northTexasGreen = { Red = 5uy; Green = 144uy; Blue = 51uy } 
        static member oceanBoatBlue = { Red = 0uy; Green = 119uy; Blue = 190uy } 
        static member ochre = { Red = 204uy; Green = 119uy; Blue = 34uy } 
        static member officeGreen = { Red = 0uy; Green = 128uy; Blue = 0uy } 
        static member oldGold = { Red = 207uy; Green = 181uy; Blue = 59uy } 
        static member oldLace = { Red = 253uy; Green = 245uy; Blue = 230uy } 
        static member oldLavender = { Red = 121uy; Green = 104uy; Blue = 120uy } 
        static member oldMauve = { Red = 103uy; Green = 49uy; Blue = 71uy } 
        static member oldRose = { Red = 192uy; Green = 128uy; Blue = 129uy } 
        static member olive = { Red = 128uy; Green = 128uy; Blue = 0uy } 
        static member oliveDrab7 = { Red = 60uy; Green = 52uy; Blue = 31uy } 
        static member oliveDrabWebOliveDrab3 = { Red = 107uy; Green = 142uy; Blue = 35uy } 
        static member olivine = { Red = 154uy; Green = 185uy; Blue = 115uy } 
        static member onyx = { Red = 53uy; Green = 56uy; Blue = 57uy } 
        static member operaMauve = { Red = 183uy; Green = 132uy; Blue = 167uy } 
        static member orangeColorWheel = { Red = 255uy; Green = 127uy; Blue = 0uy } 
        static member orangePeel = { Red = 255uy; Green = 159uy; Blue = 0uy } 
        static member orangeRed = { Red = 255uy; Green = 69uy; Blue = 0uy } 
        static member orangeRyb = { Red = 251uy; Green = 153uy; Blue = 2uy } 
        static member orangeWebColor = { Red = 255uy; Green = 165uy; Blue = 0uy } 
        static member orchid = { Red = 218uy; Green = 112uy; Blue = 214uy } 
        static member otterBrown = { Red = 101uy; Green = 67uy; Blue = 33uy } 
        static member ouCrimsonRed = { Red = 153uy; Green = 0uy; Blue = 0uy } 
        static member outerSpace = { Red = 65uy; Green = 74uy; Blue = 76uy } 
        static member outrageousOrange = { Red = 255uy; Green = 110uy; Blue = 74uy } 
        static member oxfordBlue = { Red = 0uy; Green = 33uy; Blue = 71uy } 
        static member pakistanGreen = { Red = 0uy; Green = 102uy; Blue = 0uy } 
        static member palatinateBlue = { Red = 39uy; Green = 59uy; Blue = 226uy } 
        static member palatinatePurple = { Red = 104uy; Green = 40uy; Blue = 96uy } 
        static member paleAqua = { Red = 188uy; Green = 212uy; Blue = 230uy } 
        static member paleBlue = { Red = 175uy; Green = 238uy; Blue = 238uy } 
        static member paleBrown = { Red = 152uy; Green = 118uy; Blue = 84uy } 
        static member paleCarmine = { Red = 175uy; Green = 64uy; Blue = 53uy } 
        static member paleCerulean = { Red = 155uy; Green = 196uy; Blue = 226uy } 
        static member paleChestnut = { Red = 221uy; Green = 173uy; Blue = 175uy } 
        static member paleCopper = { Red = 218uy; Green = 138uy; Blue = 103uy } 
        static member paleCornflowerBlue = { Red = 171uy; Green = 205uy; Blue = 239uy } 
        static member paleGold = { Red = 230uy; Green = 190uy; Blue = 138uy } 
        static member paleGoldenrod = { Red = 238uy; Green = 232uy; Blue = 170uy } 
        static member paleGreen = { Red = 152uy; Green = 251uy; Blue = 152uy } 
        static member paleLavender = { Red = 220uy; Green = 208uy; Blue = 255uy } 
        static member paleMagenta = { Red = 249uy; Green = 132uy; Blue = 229uy } 
        static member palePink = { Red = 250uy; Green = 218uy; Blue = 221uy } 
        static member palePlum = { Red = 221uy; Green = 160uy; Blue = 221uy } 
        static member paleRedViolet = { Red = 219uy; Green = 112uy; Blue = 147uy } 
        static member paleRobinEggBlue = { Red = 150uy; Green = 222uy; Blue = 209uy } 
        static member paleSilver = { Red = 201uy; Green = 192uy; Blue = 187uy } 
        static member paleSpringBud = { Red = 236uy; Green = 235uy; Blue = 189uy } 
        static member paleTaupe = { Red = 188uy; Green = 152uy; Blue = 126uy } 
        static member paleVioletRed = { Red = 219uy; Green = 112uy; Blue = 147uy } 
        static member pansyPurple = { Red = 120uy; Green = 24uy; Blue = 74uy } 
        static member papayaWhip = { Red = 255uy; Green = 239uy; Blue = 213uy } 
        static member parisGreen = { Red = 80uy; Green = 200uy; Blue = 120uy } 
        static member pastelBlue = { Red = 174uy; Green = 198uy; Blue = 207uy } 
        static member pastelBrown = { Red = 131uy; Green = 105uy; Blue = 83uy } 
        static member pastelGray = { Red = 207uy; Green = 207uy; Blue = 196uy } 
        static member pastelGreen = { Red = 119uy; Green = 221uy; Blue = 119uy } 
        static member pastelMagenta = { Red = 244uy; Green = 154uy; Blue = 194uy } 
        static member pastelOrange = { Red = 255uy; Green = 179uy; Blue = 71uy } 
        static member pastelPink = { Red = 222uy; Green = 165uy; Blue = 164uy } 
        static member pastelPurple = { Red = 179uy; Green = 158uy; Blue = 181uy } 
        static member pastelRed = { Red = 255uy; Green = 105uy; Blue = 97uy } 
        static member pastelViolet = { Red = 203uy; Green = 153uy; Blue = 201uy } 
        static member pastelYellow = { Red = 253uy; Green = 253uy; Blue = 150uy } 
        static member patriarch = { Red = 128uy; Green = 0uy; Blue = 128uy } 
        static member payneSGrey = { Red = 83uy; Green = 104uy; Blue = 120uy } 
        static member peach = { Red = 255uy; Green = 229uy; Blue = 180uy } 
        static member peachCrayola = { Red = 255uy; Green = 203uy; Blue = 164uy } 
        static member peachOrange = { Red = 255uy; Green = 204uy; Blue = 153uy } 
        static member peachPuff = { Red = 255uy; Green = 218uy; Blue = 185uy } 
        static member peachYellow = { Red = 250uy; Green = 223uy; Blue = 173uy } 
        static member pear = { Red = 209uy; Green = 226uy; Blue = 49uy } 
        static member pearl = { Red = 234uy; Green = 224uy; Blue = 200uy } 
        static member pearlAqua = { Red = 136uy; Green = 216uy; Blue = 192uy } 
        static member pearlyPurple = { Red = 183uy; Green = 104uy; Blue = 162uy } 
        static member peridot = { Red = 230uy; Green = 226uy; Blue = 0uy } 
        static member periwinkle = { Red = 204uy; Green = 204uy; Blue = 255uy } 
        static member persianBlue = { Red = 28uy; Green = 57uy; Blue = 187uy } 
        static member persianGreen = { Red = 0uy; Green = 166uy; Blue = 147uy } 
        static member persianIndigo = { Red = 50uy; Green = 18uy; Blue = 122uy } 
        static member persianOrange = { Red = 217uy; Green = 144uy; Blue = 88uy } 
        static member persianPink = { Red = 247uy; Green = 127uy; Blue = 190uy } 
        static member persianPlum = { Red = 112uy; Green = 28uy; Blue = 28uy } 
        static member persianRed = { Red = 204uy; Green = 51uy; Blue = 51uy } 
        static member persianRose = { Red = 254uy; Green = 40uy; Blue = 162uy } 
        static member persimmon = { Red = 236uy; Green = 88uy; Blue = 0uy } 
        static member peru = { Red = 205uy; Green = 133uy; Blue = 63uy } 
        static member phlox = { Red = 223uy; Green = 0uy; Blue = 255uy } 
        static member phthaloBlue = { Red = 0uy; Green = 15uy; Blue = 137uy } 
        static member phthaloGreen = { Red = 18uy; Green = 53uy; Blue = 36uy } 
        static member piggyPink = { Red = 253uy; Green = 221uy; Blue = 230uy } 
        static member pineGreen = { Red = 1uy; Green = 121uy; Blue = 111uy } 
        static member pink = { Red = 255uy; Green = 192uy; Blue = 203uy } 
        static member pinkLace = { Red = 255uy; Green = 221uy; Blue = 244uy } 
        static member pinkOrange = { Red = 255uy; Green = 153uy; Blue = 102uy } 
        static member pinkPearl = { Red = 231uy; Green = 172uy; Blue = 207uy } 
        static member pinkSherbet = { Red = 247uy; Green = 143uy; Blue = 167uy } 
        static member pistachio = { Red = 147uy; Green = 197uy; Blue = 114uy } 
        static member platinum = { Red = 229uy; Green = 228uy; Blue = 226uy } 
        static member plumTraditional = { Red = 142uy; Green = 69uy; Blue = 133uy } 
        static member plumWeb = { Red = 221uy; Green = 160uy; Blue = 221uy } 
        static member portlandOrange = { Red = 255uy; Green = 90uy; Blue = 54uy } 
        static member powderBlueWeb = { Red = 176uy; Green = 224uy; Blue = 230uy } 
        static member princetonOrange = { Red = 255uy; Green = 143uy; Blue = 0uy } 
        static member prune = { Red = 112uy; Green = 28uy; Blue = 28uy } 
        static member prussianBlue = { Red = 0uy; Green = 49uy; Blue = 83uy } 
        static member psychedelicPurple = { Red = 223uy; Green = 0uy; Blue = 255uy } 
        static member puce = { Red = 204uy; Green = 136uy; Blue = 153uy } 
        static member pumpkin = { Red = 255uy; Green = 117uy; Blue = 24uy } 
        static member purpleHeart = { Red = 105uy; Green = 53uy; Blue = 156uy } 
        static member purpleHtmlCss = { Red = 128uy; Green = 0uy; Blue = 128uy } 
        static member purpleMountainMajesty = { Red = 150uy; Green = 120uy; Blue = 182uy } 
        static member purpleMunsell = { Red = 159uy; Green = 0uy; Blue = 197uy } 
        static member purplePizzazz = { Red = 254uy; Green = 78uy; Blue = 218uy } 
        static member purpleTaupe = { Red = 80uy; Green = 64uy; Blue = 77uy } 
        static member purpleX11 = { Red = 160uy; Green = 32uy; Blue = 240uy } 
        static member quartz = { Red = 81uy; Green = 72uy; Blue = 79uy } 
        static member rackley = { Red = 93uy; Green = 138uy; Blue = 168uy } 
        static member radicalRed = { Red = 255uy; Green = 53uy; Blue = 94uy } 
        static member rajah = { Red = 251uy; Green = 171uy; Blue = 96uy } 
        static member raspberry = { Red = 227uy; Green = 11uy; Blue = 93uy } 
        static member raspberryGlace = { Red = 145uy; Green = 95uy; Blue = 109uy } 
        static member raspberryPink = { Red = 226uy; Green = 80uy; Blue = 152uy } 
        static member raspberryRose = { Red = 179uy; Green = 68uy; Blue = 108uy } 
        static member rawUmber = { Red = 130uy; Green = 102uy; Blue = 68uy } 
        static member razzleDazzleRose = { Red = 255uy; Green = 51uy; Blue = 204uy } 
        static member razzmatazz = { Red = 227uy; Green = 37uy; Blue = 107uy } 
        static member red = { Red = 255uy; Green = 0uy; Blue = 0uy } 
        static member redBrown = { Red = 165uy; Green = 42uy; Blue = 42uy } 
        static member redDevil = { Red = 134uy; Green = 1uy; Blue = 17uy } 
        static member redMunsell = { Red = 242uy; Green = 0uy; Blue = 60uy } 
        static member redNcs = { Red = 196uy; Green = 2uy; Blue = 51uy } 
        static member redOrange = { Red = 255uy; Green = 83uy; Blue = 73uy } 
        static member redPigment = { Red = 237uy; Green = 28uy; Blue = 36uy } 
        static member redRyb = { Red = 254uy; Green = 39uy; Blue = 18uy } 
        static member redViolet = { Red = 199uy; Green = 21uy; Blue = 133uy } 
        static member redwood = { Red = 171uy; Green = 78uy; Blue = 82uy } 
        static member regalia = { Red = 82uy; Green = 45uy; Blue = 128uy } 
        static member resolutionBlue = { Red = 0uy; Green = 35uy; Blue = 135uy } 
        static member richBlack = { Red = 0uy; Green = 64uy; Blue = 64uy } 
        static member richBrilliantLavender = { Red = 241uy; Green = 167uy; Blue = 254uy } 
        static member richCarmine = { Red = 215uy; Green = 0uy; Blue = 64uy } 
        static member richElectricBlue = { Red = 8uy; Green = 146uy; Blue = 208uy } 
        static member richLavender = { Red = 167uy; Green = 107uy; Blue = 207uy } 
        static member richLilac = { Red = 182uy; Green = 102uy; Blue = 210uy } 
        static member richMaroon = { Red = 176uy; Green = 48uy; Blue = 96uy } 
        static member rifleGreen = { Red = 65uy; Green = 72uy; Blue = 51uy } 
        static member robinEggBlue = { Red = 0uy; Green = 204uy; Blue = 204uy } 
        static member rose = { Red = 255uy; Green = 0uy; Blue = 127uy } 
        static member roseBonbon = { Red = 249uy; Green = 66uy; Blue = 158uy } 
        static member roseEbony = { Red = 103uy; Green = 72uy; Blue = 70uy } 
        static member roseGold = { Red = 183uy; Green = 110uy; Blue = 121uy } 
        static member roseMadder = { Red = 227uy; Green = 38uy; Blue = 54uy } 
        static member rosePink = { Red = 255uy; Green = 102uy; Blue = 204uy } 
        static member roseQuartz = { Red = 170uy; Green = 152uy; Blue = 169uy } 
        static member roseTaupe = { Red = 144uy; Green = 93uy; Blue = 93uy } 
        static member roseVale = { Red = 171uy; Green = 78uy; Blue = 82uy } 
        static member rosewood = { Red = 101uy; Green = 0uy; Blue = 11uy } 
        static member rossoCorsa = { Red = 212uy; Green = 0uy; Blue = 0uy } 
        static member rosyBrown = { Red = 188uy; Green = 143uy; Blue = 143uy } 
        static member royalAzure = { Red = 0uy; Green = 56uy; Blue = 168uy } 
        static member royalBlueTraditional = { Red = 0uy; Green = 35uy; Blue = 102uy } 
        static member royalBlueWeb = { Red = 65uy; Green = 105uy; Blue = 225uy } 
        static member royalFuchsia = { Red = 202uy; Green = 44uy; Blue = 146uy } 
        static member royalPurple = { Red = 120uy; Green = 81uy; Blue = 169uy } 
        static member royalYellow = { Red = 250uy; Green = 218uy; Blue = 94uy } 
        static member rubineRed = { Red = 209uy; Green = 0uy; Blue = 86uy } 
        static member ruby = { Red = 224uy; Green = 17uy; Blue = 95uy } 
        static member rubyRed = { Red = 155uy; Green = 17uy; Blue = 30uy } 
        static member ruddy = { Red = 255uy; Green = 0uy; Blue = 40uy } 
        static member ruddyBrown = { Red = 187uy; Green = 101uy; Blue = 40uy } 
        static member ruddyPink = { Red = 225uy; Green = 142uy; Blue = 150uy } 
        static member rufous = { Red = 168uy; Green = 28uy; Blue = 7uy } 
        static member russet = { Red = 128uy; Green = 70uy; Blue = 27uy } 
        static member rust = { Red = 183uy; Green = 65uy; Blue = 14uy } 
        static member rustyRed = { Red = 218uy; Green = 44uy; Blue = 67uy } 
        static member sacramentoStateGreen = { Red = 0uy; Green = 86uy; Blue = 63uy } 
        static member saddleBrown = { Red = 139uy; Green = 69uy; Blue = 19uy } 
        static member safetyOrangeBlazeOrange = { Red = 255uy; Green = 103uy; Blue = 0uy } 
        static member saffron = { Red = 244uy; Green = 196uy; Blue = 48uy } 
        static member salmon = { Red = 255uy; Green = 140uy; Blue = 105uy } 
        static member salmonPink = { Red = 255uy; Green = 145uy; Blue = 164uy } 
        static member sand = { Red = 194uy; Green = 178uy; Blue = 128uy } 
        static member sandDune = { Red = 150uy; Green = 113uy; Blue = 23uy } 
        static member sandstorm = { Red = 236uy; Green = 213uy; Blue = 64uy } 
        static member sandyBrown = { Red = 244uy; Green = 164uy; Blue = 96uy } 
        static member sandyTaupe = { Red = 150uy; Green = 113uy; Blue = 23uy } 
        static member sangria = { Red = 146uy; Green = 0uy; Blue = 10uy } 
        static member sapGreen = { Red = 80uy; Green = 125uy; Blue = 42uy } 
        static member sapphire = { Red = 15uy; Green = 82uy; Blue = 186uy } 
        static member sapphireBlue = { Red = 0uy; Green = 103uy; Blue = 165uy } 
        static member satinSheenGold = { Red = 203uy; Green = 161uy; Blue = 53uy } 
        static member scarlet = { Red = 255uy; Green = 36uy; Blue = 0uy } 
        static member scarletCrayola = { Red = 253uy; Green = 14uy; Blue = 53uy } 
        static member schoolBusYellow = { Red = 255uy; Green = 216uy; Blue = 0uy } 
        static member screaminGreen = { Red = 118uy; Green = 255uy; Blue = 122uy } 
        static member seaBlue = { Red = 0uy; Green = 105uy; Blue = 148uy } 
        static member seaGreen = { Red = 46uy; Green = 139uy; Blue = 87uy } 
        static member sealBrown = { Red = 50uy; Green = 20uy; Blue = 20uy } 
        static member seashell = { Red = 255uy; Green = 245uy; Blue = 238uy } 
        static member selectiveYellow = { Red = 255uy; Green = 186uy; Blue = 0uy } 
        static member sepia = { Red = 112uy; Green = 66uy; Blue = 20uy } 
        static member shadow = { Red = 138uy; Green = 121uy; Blue = 93uy } 
        static member shamrockGreen = { Red = 0uy; Green = 158uy; Blue = 96uy } 
        static member shockingPink = { Red = 252uy; Green = 15uy; Blue = 192uy } 
        static member shockingPinkCrayola = { Red = 255uy; Green = 111uy; Blue = 255uy } 
        static member sienna = { Red = 136uy; Green = 45uy; Blue = 23uy } 
        static member silver = { Red = 192uy; Green = 192uy; Blue = 192uy } 
        static member sinopia = { Red = 203uy; Green = 65uy; Blue = 11uy } 
        static member skobeloff = { Red = 0uy; Green = 116uy; Blue = 116uy } 
        static member skyBlue = { Red = 135uy; Green = 206uy; Blue = 235uy } 
        static member skyMagenta = { Red = 207uy; Green = 113uy; Blue = 175uy } 
        static member slateBlue = { Red = 106uy; Green = 90uy; Blue = 205uy } 
        static member slateGray = { Red = 112uy; Green = 128uy; Blue = 144uy } 
        static member smaltDarkPowderBlue = { Red = 0uy; Green = 51uy; Blue = 153uy } 
        static member smokeyTopaz = { Red = 147uy; Green = 61uy; Blue = 65uy } 
        static member smokyBlack = { Red = 16uy; Green = 12uy; Blue = 8uy } 
        static member snow = { Red = 255uy; Green = 250uy; Blue = 250uy } 
        static member spiroDiscoBall = { Red = 15uy; Green = 192uy; Blue = 252uy } 
        static member springBud = { Red = 167uy; Green = 252uy; Blue = 0uy } 
        static member springGreen = { Red = 0uy; Green = 255uy; Blue = 127uy } 
        static member stPatrickSBlue = { Red = 35uy; Green = 41uy; Blue = 122uy } 
        static member steelBlue = { Red = 70uy; Green = 130uy; Blue = 180uy } 
        static member stilDeGrainYellow = { Red = 250uy; Green = 218uy; Blue = 94uy } 
        static member stizza = { Red = 153uy; Green = 0uy; Blue = 0uy } 
        static member stormcloud = { Red = 79uy; Green = 102uy; Blue = 106uy } 
        static member straw = { Red = 228uy; Green = 217uy; Blue = 111uy } 
        static member sunglow = { Red = 255uy; Green = 204uy; Blue = 51uy } 
        static member sunset = { Red = 250uy; Green = 214uy; Blue = 165uy } 
        static member tan = { Red = 210uy; Green = 180uy; Blue = 140uy } 
        static member tangelo = { Red = 249uy; Green = 77uy; Blue = 0uy } 
        static member tangerine = { Red = 242uy; Green = 133uy; Blue = 0uy } 
        static member tangerineYellow = { Red = 255uy; Green = 204uy; Blue = 0uy } 
        static member tangoPink = { Red = 228uy; Green = 113uy; Blue = 122uy } 
        static member taupe = { Red = 72uy; Green = 60uy; Blue = 50uy } 
        static member taupeGray = { Red = 139uy; Green = 133uy; Blue = 137uy } 
        static member teaGreen = { Red = 208uy; Green = 240uy; Blue = 192uy } 
        static member teaRoseOrange = { Red = 248uy; Green = 131uy; Blue = 121uy } 
        static member teaRoseRose = { Red = 244uy; Green = 194uy; Blue = 194uy } 
        static member teal = { Red = 0uy; Green = 128uy; Blue = 128uy } 
        static member tealBlue = { Red = 54uy; Green = 117uy; Blue = 136uy } 
        static member tealGreen = { Red = 0uy; Green = 130uy; Blue = 127uy } 
        static member telemagenta = { Red = 207uy; Green = 52uy; Blue = 118uy } 
        static member tennTawny = { Red = 205uy; Green = 87uy; Blue = 0uy } 
        static member terraCotta = { Red = 226uy; Green = 114uy; Blue = 91uy } 
        static member thistle = { Red = 216uy; Green = 191uy; Blue = 216uy } 
        static member thulianPink = { Red = 222uy; Green = 111uy; Blue = 161uy } 
        static member tickleMePink = { Red = 252uy; Green = 137uy; Blue = 172uy } 
        static member tiffanyBlue = { Red = 10uy; Green = 186uy; Blue = 181uy } 
        static member tigerSEye = { Red = 224uy; Green = 141uy; Blue = 60uy } 
        static member timberwolf = { Red = 219uy; Green = 215uy; Blue = 210uy } 
        static member titaniumYellow = { Red = 238uy; Green = 230uy; Blue = 0uy } 
        static member tomato = { Red = 255uy; Green = 99uy; Blue = 71uy } 
        static member toolbox = { Red = 116uy; Green = 108uy; Blue = 192uy } 
        static member topaz = { Red = 255uy; Green = 200uy; Blue = 124uy } 
        static member tractorRed = { Red = 253uy; Green = 14uy; Blue = 53uy } 
        static member trolleyGrey = { Red = 128uy; Green = 128uy; Blue = 128uy } 
        static member tropicalRainForest = { Red = 0uy; Green = 117uy; Blue = 94uy } 
        static member trueBlue = { Red = 0uy; Green = 115uy; Blue = 207uy } 
        static member tuftsBlue = { Red = 65uy; Green = 125uy; Blue = 193uy } 
        static member tumbleweed = { Red = 222uy; Green = 170uy; Blue = 136uy } 
        static member turkishRose = { Red = 181uy; Green = 114uy; Blue = 129uy } 
        static member turquoise = { Red = 48uy; Green = 213uy; Blue = 200uy } 
        static member turquoiseBlue = { Red = 0uy; Green = 255uy; Blue = 239uy } 
        static member turquoiseGreen = { Red = 160uy; Green = 214uy; Blue = 180uy } 
        static member tuscanRed = { Red = 124uy; Green = 72uy; Blue = 72uy } 
        static member twilightLavender = { Red = 138uy; Green = 73uy; Blue = 107uy } 
        static member tyrianPurple = { Red = 102uy; Green = 2uy; Blue = 60uy } 
        static member uaBlue = { Red = 0uy; Green = 51uy; Blue = 170uy }
        static member uaRed = { Red = 217uy; Green = 0uy; Blue = 76uy }
        static member ube = { Red = 136uy; Green = 120uy; Blue = 195uy } 
        static member uclaBlue = { Red = 83uy; Green = 104uy; Blue = 149uy } 
        static member uclaGold = { Red = 255uy; Green = 179uy; Blue = 0uy } 
        static member ufoGreen = { Red = 60uy; Green = 208uy; Blue = 112uy } 
        static member ultraPink = { Red = 255uy; Green = 111uy; Blue = 255uy } 
        static member ultramarine = { Red = 18uy; Green = 10uy; Blue = 143uy } 
        static member ultramarineBlue = { Red = 65uy; Green = 102uy; Blue = 245uy } 
        static member umber = { Red = 99uy; Green = 81uy; Blue = 71uy } 
        static member unbleachedSilk = { Red = 255uy; Green = 221uy; Blue = 202uy } 
        static member unitedNationsBlue = { Red = 91uy; Green = 146uy; Blue = 229uy } 
        static member universityOfCaliforniaGold = { Red = 183uy; Blue = 135uy; Green = 39uy } 
        static member unmellowYellow = { Red = 255uy; Green = 255uy; Blue = 102uy } 
        static member upForestGreen = { Red = 1uy; Green = 68uy; Blue = 33uy } 
        static member upMaroon = { Red = 123uy; Green = 17uy; Blue = 19uy } 
        static member upsdellRed = { Red = 174uy; Green = 32uy; Blue = 41uy } 
        static member urobilin = { Red = 225uy; Green = 173uy; Blue = 33uy } 
        static member usafaBlue = { Red = 0uy; Green = 79uy; Blue = 152uy } 
        static member uscCardinal = { Red = 153uy; Green = 0uy; Blue = 0uy } 
        static member uscGold = { Red = 255uy; Green = 204uy; Blue = 0uy } 
        static member utahCrimson = { Red = 211uy; Green = 0uy; Blue = 63uy } 
        static member vanilla = { Red = 243uy; Green = 229uy; Blue = 171uy } 
        static member vegasGold = { Red = 197uy; Green = 179uy; Blue = 88uy } 
        static member venetianRed = { Red = 200uy; Green = 8uy; Blue = 21uy } 
        static member verdigris = { Red = 67uy; Green = 179uy; Blue = 174uy }
        static member vermilionCinnabar = { Red = 227uy; Green = 66uy; Blue = 52uy } 
        static member vermilionPlochere = { Red = 217uy; Green = 96uy; Blue = 59uy } 
        static member veronica = { Red = 160uy; Green = 32uy; Blue = 240uy } 
        static member violet = { Red = 143uy; Green = 0uy; Blue = 255uy } 
        static member violetBlue = { Red = 50uy; Green = 74uy; Blue = 178uy } 
        static member violetColorWheel = { Red = 127uy; Green = 0uy; Blue = 255uy } 
        static member violetRyb = { Red = 134uy; Green = 1uy; Blue = 175uy } 
        static member violetWeb = { Red = 238uy; Green = 130uy; Blue = 238uy } 
        static member viridian = { Red = 64uy; Green = 130uy; Blue = 109uy } 
        static member vividAuburn = { Red = 146uy; Green = 39uy; Blue = 36uy } 
        static member vividBurgundy = { Red = 159uy; Green = 29uy; Blue = 53uy } 
        static member vividCerise = { Red = 218uy; Green = 29uy; Blue = 129uy } 
        static member vividTangerine = { Red = 255uy; Green = 160uy; Blue = 137uy } 
        static member vividViolet = { Red = 159uy; Green = 0uy; Blue = 255uy } 
        static member warmBlack = { Red = 0uy; Green = 66uy; Blue = 66uy } 
        static member waterspout = { Red = 164uy; Green = 244uy; Blue = 249uy } 
        static member wenge = { Red = 100uy; Green = 84uy; Blue = 82uy } 
        static member wheat = { Red = 245uy; Green = 222uy; Blue = 179uy } 
        static member white = { Red = 255uy; Green = 255uy; Blue = 255uy } 
        static member whiteSmoke = { Red = 245uy; Green = 245uy; Blue = 245uy } 
        static member wildBlueYonder = { Red = 162uy; Green = 173uy; Blue = 208uy } 
        static member wildStrawberry = { Red = 255uy; Green = 67uy; Blue = 164uy } 
        static member wildWatermelon = { Red = 252uy; Green = 108uy; Blue = 133uy } 
        static member wine = { Red = 114uy; Green = 47uy; Blue = 55uy } 
        static member wineDregs = { Red = 103uy; Green = 49uy; Blue = 71uy } 
        static member wisteria = { Red = 201uy; Green = 160uy; Blue = 220uy } 
        static member woodBrown = { Red = 193uy; Green = 154uy; Blue = 107uy } 
        static member xanadu = { Red = 115uy; Green = 134uy; Blue = 120uy } 
        static member yaleBlue = { Red = 15uy; Green = 77uy; Blue = 146uy } 
        static member yellow = { Red = 255uy; Green = 255uy; Blue = 0uy } 
        static member yellowGreen = { Red = 154uy; Green = 205uy; Blue = 50uy } 
        static member yellowMunsell = { Red = 239uy; Green = 204uy; Blue = 0uy } 
        static member yellowNcs = { Red = 255uy; Green = 211uy; Blue = 0uy } 
        static member yellowOrange = { Red = 255uy; Green = 174uy; Blue = 66uy } 
        static member yellowProcess = { Red = 255uy; Green = 239uy; Blue = 0uy } 
        static member yellowRyb = { Red = 254uy; Green = 254uy; Blue = 51uy } 
        static member zaffre = { Red = 0uy; Green = 20uy; Blue = 168uy } 
        static member zinnwalditeBrown = { Red = 44uy; Green = 22uy; Blue = 8uy }